project:
  type: website
  post-render:
    - _scripts/post-render.R
  
title-block-banner: "#FCEDE2"
title-block-banner-color: "#000"
reference-location: margin
citation-location: margin

format:
  soles-assignment-html:
    embed-resources: false
  soles-assignment-pdf:
    keep-tex: false
    toc: true

execute:
  freeze: auto

profile:
  default: 
    # - exercise,solution
    - exercise
    # - solution