project:
  type: website
  
title-block-banner: "#FCEDE2"
title-block-banner-color: "#000"

format:
  soles-assignment-html:
    embed-resources: true
  soles-assignment-pdf:
    keep-tex: false
    toc: true

execute:
  freeze: true

profile:
  default: exercise